### ISSUE TITLE
server: issuers aren't properly deleted

### ISSUE THREAD

**Issue by timber-they** [mint-o-badges/badgr-server#240]
When deleting an issuer, an error message is displayed and the issuer is still displayed. It seems to be deleted in the database (it disappears from the staff frontend), but it still exists in the ui. It seems to be a caching error.

For the initial deletion, an error 500 is logged in the browser console. In the backend, this error is logged:
```python
api-1  | Internal Server Error: /v1/issuer/issuers/ozVkudfrRiyM36pjdX8PwQ
api-1  | Traceback (most recent call last):
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 173, in __get__
api-1  |     rel_obj = self.field.get_cached_value(instance)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
api-1  |     return instance._state.fields_cache[cache_name]
api-1  | KeyError: 'issuer'
api-1  | 
api-1  | During handling of the above exception, another exception occurred:
api-1  | 
api-1  | Traceback (most recent call last):
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
api-1  |     response = get_response(request)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
api-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
api-1  |     return view_func(*args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
api-1  |     return self.dispatch(request, *args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
api-1  |     response = self.handle_exception(exc)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
api-1  |     self.raise_uncaught_exception(exc)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
api-1  |     raise exc
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
api-1  |     response = handler(request, *args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/apispec_drf/decorators.py", line 100, in wrapper
api-1  |     return wrapped(*args, **kwargs)
api-1  |   File "/badgr_server/apps/issuer/api.py", line 104, in delete
api-1  |     return super(IssuerDetail, self).delete(request, **kwargs)
api-1  |   File "/badgr_server/apps/entity/api.py", line 173, in delete
api-1  |     obj.delete()
api-1  |   File "/badgr_server/apps/issuer/models.py", line 251, in delete
api-1  |     membership.delete(publish_issuer=False)
api-1  |   File "/badgr_server/apps/issuer/models.py", line 622, in delete
api-1  |     new_contact = self.is_staff_contact()
api-1  |   File "/badgr_server/apps/issuer/models.py", line 637, in is_staff_contact
api-1  |     issuer_email = self.issuer.email
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 187, in __get__
api-1  |     rel_obj = self.get_object(instance)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 154, in get_object
api-1  |     return qs.get(self.field.get_reverse_related_filter(instance))
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
api-1  |     raise self.model.DoesNotExist(
api-1  | issuer.models.Issuer.DoesNotExist: Issuer matching query does not exist.
```

After deleting, this is the error message:
![Image](https://github.com/user-attachments/assets/c89982a2-b0c3-4f63-a6cc-e12d0443f733)

In the console the error is:
```js
scripts.c0ab17febce06d11.js:1 Uncaught SyntaxError: Unexpected token 'export'
main.eea635a2d42cd998.js:4 lng: de
api.staging.openbadges.education/v1/issuer/issuers/3WdBf-B8SIaRbKzGxEekOw:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
main.eea635a2d42cd998.js:4 Failed to delete issuer v: {"detail":"Not found."}
    at k (https://staging.openbadges.education/main.eea635a2d42cd998.js:4:662121)
    at https://staging.openbadges.education/main.eea635a2d42cd998.js:4:662473
    at v.invoke (https://staging.openbadges.education/polyfills.0b69a40efa0a1b76.js:1:29792)
    at Object.onInvoke (https://staging.openbadges.education/main.eea635a2d42cd998.js:132:1522286)
    at v.invoke (https://staging.openbadges.education/polyfills.0b69a40efa0a1b76.js:1:29732)
    at v.run (https://staging.openbadges.education/polyfills.0b69a40efa0a1b76.js:1:24605)
    at https://staging.openbadges.education/polyfills.0b69a40efa0a1b76.js:1:18463
    at v.invokeTask (https://staging.openbadges.education/polyfills.0b69a40efa0a1b76.js:1:30476)
    at Object.onInvokeTask (https://staging.openbadges.education/main.eea635a2d42cd998.js:132:1522099)
    at v.invokeTask (https://staging.openbadges.education/polyfills.0b69a40efa0a1b76.js:1:30397)
reportHandledError @ main.eea635a2d42cd998.js:4
```

**Comment by zven** [comment]
@jona159 Looks like the error Annika has encountered as well. ;-)

**Comment by jona159** [comment]
The problem was that it tries to access issuer.email after the issuer is deleted, as shown in the error
