### ISSUE TITLE
server: QR-Code Download fails

### ISSUE THREAD

**Issue by timber-they** [mint-o-badges/badgr-server#247]
Currently on Staging, the QR-Code download fails with an error 500. I observed this while testing with the E2E-tests. This is the log message:
```python
api-1  | Internal Server Error: /download-qrcode/nEjp0KiWRJu5bjhWbqOH9w/tRRUtBThTKqDAeuncWe2Gw
api-1  | Traceback (most recent call last):
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 655, in __init__
api-1  |     self.fp = open_for_read(fileName,'b')
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 535, in open_for_read
api-1  |     if hasattr(name,'read'): return name
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/files/utils.py", line 16, in <lambda>
api-1  |     read = property(lambda self: self.file.read)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/fields/files.py", line 42, in _get_file
api-1  |     self._require_file()
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/fields/files.py", line 39, in _require_file
api-1  |     raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
api-1  | ValueError: The 'image' attribute has no file associated with it.
api-1  | 
api-1  | During handling of the above exception, another exception occurred:
api-1  | 
api-1  | Traceback (most recent call last):
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 164, in apply
api-1  |     getattr(doc,arn)(*args)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 1290, in handle_pageBegin
api-1  |     self._handle_pageBegin()
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 617, in handle_pageBegin
api-1  |     self.pageTemplate.onPage(self.canv,self)
api-1  |   File "/badgr_server/apps/mainsite/views.py", line 349, in <lambda>
api-1  |     doc.build(Story, onFirstPage=lambda canvas, doc: PageSetup(canvas, doc, badgeImage, issuerImage))
api-1  |   File "/badgr_server/apps/mainsite/views.py", line 256, in PageSetup
api-1  |     institutionImage = ImageReader(issuerImage)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 696, in __init__
api-1  |     annotateException('\nfileName=%r identity=%s'%(fileName,self.identity()))
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 1223, in annotateException
api-1  |     rl_reraise(t,t(sep.join((_ for _ in (msg,str(v),postMsg) if _))),b)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 141, in rl_reraise
api-1  |     raise v.with_traceback(b)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 655, in __init__
api-1  |     self.fp = open_for_read(fileName,'b')
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 535, in open_for_read
api-1  |     if hasattr(name,'read'): return name
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/files/utils.py", line 16, in <lambda>
api-1  |     read = property(lambda self: self.file.read)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/fields/files.py", line 42, in _get_file
api-1  |     self._require_file()
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/fields/files.py", line 39, in _require_file
api-1  |     raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
api-1  | ValueError: 
api-1  | fileName=<FieldFile: None> identity=[ImageReader@0x7f700a6e2880] The 'image' attribute has no file associated with it.
api-1  | 
api-1  | During handling of the above exception, another exception occurred:
api-1  | 
api-1  | Traceback (most recent call last):
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
api-1  |     response = get_response(request)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
api-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
api-1  |     return view_func(*args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
api-1  |     return self.dispatch(request, *args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
api-1  |     response = self.handle_exception(exc)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
api-1  |     self.raise_uncaught_exception(exc)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
api-1  |     raise exc
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
api-1  |     response = handler(request, *args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
api-1  |     return func(*args, **kwargs)
api-1  |   File "/badgr_server/apps/mainsite/views.py", line 412, in downloadQrCode
api-1  |     create_page(response, Story, badgeImage, issuerImage)
api-1  |   File "/badgr_server/apps/mainsite/views.py", line 349, in create_page
api-1  |     doc.build(Story, onFirstPage=lambda canvas, doc: PageSetup(canvas, doc, badgeImage, issuerImage))
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 1314, in build
api-1  |     BaseDocTemplate.build(self,flowables, canvasmaker=canvasmaker)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 1076, in build
api-1  |     self.clean_hanging()
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 588, in clean_hanging
api-1  |     self.handle_flowable(self._hanging)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 922, in handle_flowable
api-1  |     f.apply(self)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 171, in apply
api-1  |     annotateException("\nhandle_%s args=%s"%(action,ascii(args)))
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 1223, in annotateException
api-1  |     rl_reraise(t,t(sep.join((_ for _ in (msg,str(v),postMsg) if _))),b)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 141, in rl_reraise
api-1  |     raise v.with_traceback(b)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 164, in apply
api-1  |     getattr(doc,arn)(*args)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 1290, in handle_pageBegin
api-1  |     self._handle_pageBegin()
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/platypus/doctemplate.py", line 617, in handle_pageBegin
api-1  |     self.pageTemplate.onPage(self.canv,self)
api-1  |   File "/badgr_server/apps/mainsite/views.py", line 349, in <lambda>
api-1  |     doc.build(Story, onFirstPage=lambda canvas, doc: PageSetup(canvas, doc, badgeImage, issuerImage))
api-1  |   File "/badgr_server/apps/mainsite/views.py", line 256, in PageSetup
api-1  |     institutionImage = ImageReader(issuerImage)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 696, in __init__
api-1  |     annotateException('\nfileName=%r identity=%s'%(fileName,self.identity()))
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 1223, in annotateException
api-1  |     rl_reraise(t,t(sep.join((_ for _ in (msg,str(v),postMsg) if _))),b)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 141, in rl_reraise
api-1  |     raise v.with_traceback(b)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 655, in __init__
api-1  |     self.fp = open_for_read(fileName,'b')
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 535, in open_for_read
api-1  |     if hasattr(name,'read'): return name
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/files/utils.py", line 16, in <lambda>
api-1  |     read = property(lambda self: self.file.read)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/fields/files.py", line 42, in _get_file
api-1  |     self._require_file()
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/fields/files.py", line 39, in _require_file
api-1  |     raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
api-1  | ValueError: 
api-1  | handle_pageBegin args=() 
api-1  | fileName=<FieldFile: None> identity=[ImageReader@0x7f700a6e2880] The 'image' attribute has no file associated with it.
api-1  | [pid: 12|app: 0|req: 1114/2979] 192.168.128.2 () {78 vars in 1484 bytes} [Thu Sep 26 21:55:03 2024] POST /download-qrcode/nEjp0KiWRJu5bjhWbqOH9w/tRRUtBThTKqDAeuncWe2Gw => generated 295917 bytes in 217 msecs (HTTP/1.1 500) 6 headers in 260 bytes (1 switches on core 1)
```

**Comment by zven** [comment]
Curiouos! Could the test setup be related to that error? I tested the QR-Code-Download on Firefox and Chrome without issues.

**Comment by timber-they** [comment]
@zven It seems that this has been "fixed" by [this ticket](https://github.com/orgs/mint-o-badges/projects/2/views/1?pane=issue&itemId=75865530), I guess. Either way: An error 500 is always a server error and should in my opinion be fixed. The linked ticket afaik only made UI adjustments, so it didn't fix the server error. But I guess it has a lower priority then.

**Comment by jona159** [comment]
@timber-they Sorry i didnt link the PR here, the issue was fixed on the server by [this](https://github.com/mint-o-badges/badgr-server/pull/248) PR
