### ISSUE TITLE
server: Creating user sometimes fails

### ISSUE THREAD

**Issue by timber-they** [mint-o-badges/badgr-server#250]
When running the E2E tests, the user creation sometimes fails. This is a bug, because it's caused by a server error. These are the relevant server logs:
```python
api-1  | Internal Server Error: /v1/user/profile
api-1  | Traceback (most recent call last):
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
api-1  |     return self.get(**kwargs), False
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
api-1  |     raise self.model.DoesNotExist(
api-1  | rest_framework.authtoken.models.Token.DoesNotExist: Token matching query does not exist.
api-1  | 
api-1  | During handling of the above exception, another exception occurred:
api-1  | 
api-1  | Traceback (most recent call last):
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
api-1  |     return self.cursor.execute(sql, params)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
api-1  |     return self.cursor.execute(query, args)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
api-1  |     res = self._query(query)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
api-1  |     db.query(q)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
api-1  |     _mysql.connection.query(self, query)
api-1  | MySQLdb._exceptions.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`badgr`.`authtoken_token`, CONSTRAINT `authtoken_token_user_id_35299eff_fk_users_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))')
api-1  | 
api-1  | The above exception was the direct cause of the following exception:
api-1  | 
api-1  | Traceback (most recent call last):
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
api-1  |     response = get_response(request)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
api-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
api-1  |     return view_func(*args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
api-1  |     return self.dispatch(request, *args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
api-1  |     response = self.handle_exception(exc)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
api-1  |     self.raise_uncaught_exception(exc)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
api-1  |     raise exc
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
api-1  |     response = handler(request, *args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/apispec_drf/decorators.py", line 154, in wrapper
api-1  |     return wrapped(*args, **kwargs)
api-1  |   File "/badgr_server/apps/mainsite/utils.py", line 397, in wrapper
api-1  |     raise e
api-1  |   File "/badgr_server/apps/mainsite/utils.py", line 378, in wrapper
api-1  |     result = f(*args, **kw)  # execute the decorated function
api-1  |   File "/badgr_server/apps/badgeuser/api.py", line 133, in post
api-1  |     serializer.save()
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
api-1  |     self.instance = self.create(validated_data)
api-1  |   File "/badgr_server/apps/badgeuser/serializers_v1.py", line 90, in create
api-1  |     user = BadgeUser.objects.create(
api-1  |   File "/badgr_server/apps/badgeuser/managers.py", line 67, in create
api-1  |     existing_email.delete()
api-1  |   File "/badgr_server/apps/badgeuser/models.py", line 67, in delete
api-1  |     user.publish()
api-1  |   File "/badgr_server/apps/badgeuser/models.py", line 246, in publish
api-1  |     super(BadgeUser, self).publish()
api-1  |   File "/badgr_server/apps/entity/models.py", line 29, in publish
api-1  |     super(_AbstractVersionedEntity, self).publish()
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/cachemodel/models.py", line 58, in publish
api-1  |     self.publish_method(method.__name__)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/cachemodel/models.py", line 89, in publish_method
api-1  |     data = target(self, *args, **kwargs)
api-1  |   File "/badgr_server/apps/badgeuser/models.py", line 484, in cached_token
api-1  |     Token.objects.get_or_create(user=self)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
api-1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/query.py", line 588, in get_or_create
api-1  |     return self.create(**params), True
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
api-1  |     obj.save(force_insert=True, using=self.db)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/authtoken/models.py", line 33, in save
api-1  |     return super().save(*args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/base.py", line 726, in save
api-1  |     self.save_base(using=using, force_insert=force_insert,
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/base.py", line 763, in save_base
api-1  |     updated = self._save_table(
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/base.py", line 868, in _save_table
api-1  |     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/base.py", line 906, in _do_insert
api-1  |     return manager._insert(
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
api-1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
api-1  |     return query.get_compiler(using=using).execute_sql(returning_fields)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1410, in execute_sql
api-1  |     cursor.execute(sql, params)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
api-1  |     return super().execute(sql, params)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
api-1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
api-1  |     return executor(sql, params, many, context)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
api-1  |     return self.cursor.execute(sql, params)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
api-1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
api-1  |     return self.cursor.execute(sql, params)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
api-1  |     return self.cursor.execute(query, args)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
api-1  |     res = self._query(query)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
api-1  |     db.query(q)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
api-1  |     _mysql.connection.query(self, query)
api-1  | django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`badgr`.`authtoken_token`, CONSTRAINT `authtoken_token_user_id_35299eff_fk_users_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))')
```

In the browser console this is logged:
```js
api.staging.openbadges.education/v1/user/profile:1 
            
       Failed to load resource: the server responded with a status of 500 ()
```

This error message is displayed:
![Image](https://github.com/user-attachments/assets/65a34cd3-4564-4e56-b333-3f4e6cb7e607)

The content of the error message is this:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <title>IntegrityError
          at /v1/user/profile</title>
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background-color:#fff; color:#000; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; }
    h2 { margin-bottom:.8em; }
    h3 { margin:1em 0 .5em 0; }
    h4 { margin:0 0 .5em 0; font-weight: normal; }
    code, pre { font-size: 100%; white-space: pre-wrap; }
    table { border:1px solid #ccc; border-collapse: collapse; width:100%; background:white; }
    tbody td, tbody th { vertical-align:top; padding:2px 3px; }
    thead th {
      padding:1px 6px 1px 3px; background:#fefefe; text-align:left;
      font-weight:normal; font-size:11px; border:1px solid #ddd;
    }
    tbody th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    table.vars { margin:5px 0 2px 40px; }
    table.vars td, table.req td { font-family:monospace; }
    table td.code { width:100%; }
    table td.code pre { overflow:hidden; }
    table.source th { color:#666; }
    table.source td { font-family:monospace; white-space:pre; border-bottom:1px solid #eee; }
    ul.traceback { list-style-type:none; color: #222; }
    ul.traceback li.frame { padding-bottom:1em; color:#4f4f4f; }
    ul.traceback li.user { background-color:#e0e0e0; color:#000 }
    div.context { padding:10px 0; overflow:hidden; }
    div.context ol { padding-left:30px; margin:0 10px; list-style-position: inside; }
    div.context ol li { font-family:monospace; white-space:pre; color:#777; cursor:pointer; padding-left: 2px; }
    div.context ol li pre { display:inline; }
    div.context ol.context-line li { color:#464646; background-color:#dfdfdf; padding: 3px 2px; }
    div.context ol.context-line li span { position:absolute; right:32px; }
    .user div.context ol.context-line li { background-color:#bbb; color:#000; }
    .user div.context ol li { color:#666; }
    div.commands { margin-left: 40px; }
    div.commands a { color:#555; text-decoration:none; }
    .user div.commands a { color: black; }
    #summary { background: #ffc; }
    #summary h2 { font-weight: normal; color: #666; }
    #explanation { background:#eee; }
    #template, #template-not-exist { background:#f6f6f6; }
    #template-not-exist ul { margin: 0 0 10px 20px; }
    #template-not-exist .postmortem-section { margin-bottom: 3px; }
    #unicode-hint { background:#eee; }
    #traceback { background:#eee; }
    #requestinfo { background:#f6f6f6; padding-left:120px; }
    #summary table { border:none; background:transparent; }
    #requestinfo h2, #requestinfo h3 { position:relative; margin-left:-100px; }
    #requestinfo h3 { margin-bottom:-1em; }
    .error { background: #ffc; }
    .specific { color:#cc3300; font-weight:bold; }
    h2 span.commands { font-size:.7em; font-weight:normal; }
    span.commands a:link {color:#5E5694;}
    pre.exception_value { font-family: sans-serif; color: #575757; font-size: 1.5em; margin: 10px 0 10px 0; }
    .append-bottom { margin-bottom: 10px; }
    .fname { user-select: all; }
  </style>
  
  <script>
    function hideAll(elems) {
      for (var e = 0; e < elems.length; e++) {
        elems[e].style.display = 'none';
      }
    }
    window.onload = function() {
      hideAll(document.querySelectorAll('table.vars'));
      hideAll(document.querySelectorAll('ol.pre-context'));
      hideAll(document.querySelectorAll('ol.post-context'));
      hideAll(document.querySelectorAll('div.pastebin'));
    }
    function toggle() {
      for (var i = 0; i < arguments.length; i++) {
        var e = document.getElementById(arguments[i]);
        if (e) {
          e.style.display = e.style.display == 'none' ? 'block': 'none';
        }
      }
      return false;
    }
    function varToggle(link, id) {
      toggle('v' + id);
      var s = link.getElementsByTagName('span')[0];
      var uarr = String.fromCharCode(0x25b6);
      var darr = String.fromCharCode(0x25bc);
      s.textContent = s.textContent == uarr ? darr : uarr;
      return false;
    }
    function switchPastebinFriendly(link) {
      s1 = "Switch to copy-and-paste view";
      s2 = "Switch back to interactive view";
      link.textContent = link.textContent.trim() == s1 ? s2: s1;
      toggle('browserTraceback', 'pastebinTraceback');
      return false;
    }
  </script>
  
</head>
<body>
<div id="summary">
  <h1>IntegrityError
       at /v1/user/profile</h1>
  <pre class="exception_value">(1452, &#x27;Cannot add or update a child row: a foreign key constraint fails (`badgr`.`authtoken_token`, CONSTRAINT `authtoken_token_user_id_35299eff_fk_users_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))&#x27;)</pre>
  <table class="meta">

    <tr>
      <th>Request Method:</th>
      <td>POST</td>
    </tr>
    <tr>
      <th>Request URL:</th>
      <td>https://api.staging.openbadges.education/v1/user/profile</td>
    </tr>

    <tr>
      <th>Django Version:</th>
      <td>3.2</td>
    </tr>

    <tr>
      <th>Exception Type:</th>
      <td>IntegrityError</td>
    </tr>


    <tr>
      <th>Exception Value:</th>
      <td><pre>(1452, &#x27;Cannot add or update a child row: a foreign key constraint fails (`badgr`.`authtoken_token`, CONSTRAINT `authtoken_token_user_id_35299eff_fk_users_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))&#x27;)</pre></td>
    </tr>


    <tr>
      <th>Exception Location:</th>
      <td><span class="fname">/badgr_server/venv/lib/python3.8/site-packages/MySQLdb/connections.py</span>, line 239, in query</td>
    </tr>

    <tr>
      <th>Python Executable:</th>
      <td>/badgr_server/venv/bin/uwsgi</td>
    </tr>
    <tr>
      <th>Python Version:</th>
      <td>3.8.14</td>
    </tr>
    <tr>
      <th>Python Path:</th>
      <td><pre>[&#x27;/badgr_server/apps&#x27;,
 &#x27;.&#x27;,
 &#x27;&#x27;,
 &#x27;/usr/local/lib/python38.zip&#x27;,
 &#x27;/usr/local/lib/python3.8&#x27;,
 &#x27;/usr/local/lib/python3.8/lib-dynload&#x27;,
 &#x27;/badgr_server/venv/lib/python3.8/site-packages&#x27;,
 &#x27;/badgr_server&#x27;]</pre></td>
    </tr>
    <tr>
      <th>Server time:</th>
      <td>Fri, 27 Sep 2024 15:24:49 +0200</td>
    </tr>
  </table>
</div>




<div id="traceback">
  <h2>Traceback <span class="commands"><a href="#" onclick="return switchPastebinFriendly(this);">
    Switch to copy-and-paste view</a></span>
  </h2>
  <div id="browserTraceback">
    <ul class="traceback">
      
        
        <li class="frame django">
          
            <code class="fname">/badgr_server/venv/lib/python3.8/site-packages/django/db/models/query.py</code>, line 581, in get_or_create
          

          
            <div class="context" id="c140600079575616">
              
                <ol start="574" class="pre-context" id="pre140600079575616">
                
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        Return a tuple of (object, created), where created is a boolean</pre></li>
                
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        specifying whether an object was created.</pre></li>
                
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        &quot;&quot;&quot;</pre></li>
                
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        # The get() needs to be targeted at the write database in order</pre></li>
                
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        # to avoid potential transaction consistency problems.</pre></li>
                
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        self._for_write = True</pre></li>
                
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        try:</pre></li>
                
                </ol>
              
              <ol start="581" class="context-line">
                <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>            return self.get(**kwargs), False</pre> <span>…</span></li>
              </ol>
              
                <ol start='582' class="post-context" id="post140600079575616">
                  
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        except self.model.DoesNotExist:</pre></li>
                  
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>            params = self._extract_model_params(defaults, **kwargs)</pre></li>
                  
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>            # Try to create an object using passed params.</pre></li>
                  
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>            try:</pre></li>
                  
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>                with transaction.atomic(using=self.db):</pre></li>
                  
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>                    params = dict(resolve_callables(params))</pre></li>
                  
              </ol>
              
            </div>
          

          
            <div class="commands">
                
                    <a href="#" onclick="return varToggle(this, '140600079575616')"><span>&#x25b6;</span> Local vars</a>
                <!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <title>IntegrityError
          at /v1/user/profile</title>
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background-color:#fff; color:#000; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; }
    h2 { margin-bottom:.8em; }
    h3 { margin:1em 0 .5em 0; }
    h4 { margin:0 0 .5em 0; font-weight: normal; }
    code, pre { font-size: 100%; white-space: pre-wrap; }
    table { border:1px solid #ccc; border-collapse: collapse; width:100%; background:white; }
    tbody td, tbody th { vertical-align:top; padding:2px 3px; }
    thead th {
      padding:1px 6px 1px 3px; background:#fefefe; text-align:left;
      font-weight:normal; font-size:11px; border:1px solid #ddd;
    }
    tbody th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    table.vars { margin:5px 0 2px 40px; }
    table.vars td, table.req td { font-family:monospace; }
    table td.code { width:100%; }
    table td.code pre { overflow:hidden; }
    table.source th { color:#666; }
    table.source td { font-family:monospace; white-space:pre; border-bottom:1px solid #eee; }
    ul.traceback { list-style-type:none; color: #222; }
    ul.traceback li.frame { padding-bottom:1em; color:#4f4f4f; }
    ul.traceback li.user { background-color:#e0e0e0; color:#000 }
    div.context { padding:10px 0; overflow:hidden; }
    div.context ol { padding-left:30px; margin:0 10px; list-style-position: inside; }
    div.context ol li { font-family:monospace; white-space:pre; color:#777; cursor:pointer; padding-left: 2px; }
    div.context ol li pre { display:inline; }
    div.context ol.context-line li { color:#464646; background-color:#dfdfdf; padding: 3px 2px; }
    div.context ol.context-line li span { position:absolute; right:32px; }
    .user div.context ol.context-line li { background-color:#bbb; color:#000; }
    .user div.context ol li { color:#666; }
    div.commands { margin-left: 40px; }
    div.commands a { color:#555; text-decoration:none; }
    .user div.commands a { color: black; }
    #summary { background: #ffc; }
    #summary h2 { font-weight: normal; color: #666; }
    #explanation { background:#eee; }
    #template, #template-not-exist { background:#f6f6f6; }
    #template-not-exist ul { margin: 0 0 10px 20px; }
    #template-not-exist .postmortem-section { margin-bottom: 3px; }
    #unicode-hint { background:#eee; }
    #traceback { background:#eee; }
    #requestinfo { background:#f6f6f6; padding-left:120px; }
    #summary table { border:none; background:transparent; }
    #requestinfo h2, #requestinfo h3 { position:relative; margin-left:-100px; }
    #requestinfo h3 { margin-bottom:-1em; }
    .error { background: #ffc; }
    .specific { color:#cc3300; font-weight:bold; }
    h2 span.commands { font-size:.7em; font-weight:normal; }
    span.commands a:link {color:#5E5694;}
    pre.exception_value { font-family: sans-serif; color: #575757; font-size: 1.5em; margin: 10px 0 10px 0; }
    .append-bottom { margin-bottom: 10px; }
    .fname { user-select: all; }
  </style>
  
  <script>
    function hideAll(elems) {
      for (var e = 0; e < elems.length; e++) {
        elems[e].style.display = 'none';
      }
    }
    window.onload = function() {
      hideAll(document.querySelectorAll('table.vars'));
      hideAll(document.querySelectorAll('ol.pre-context'));
      hideAll(document.querySelectorAll('ol.post-context'));
      hideAll(document.querySelectorAll('div.pastebin'));
    }
    function toggle() {
      for (var i = 0; i < arguments.length; i++) {
        var e = document.getElementById(arguments[i]);
        if (e) {
          e.style.display = e.style.display == 'none' ? 'block': 'none';
        }
      }
      return false;
    }
    function varToggle(link, id) {
      toggle('v' + id);
      var s = link.getElementsByTagName('span')[0];
      var uarr = String.fromCharCode(0x25b6);
      var darr = String.fromCharCode(0x25bc);
      s.textContent = s.textContent == uarr ? darr : uarr;
      return false;
    }
    function switchPastebinFriendly(link) {
      s1 = "Switch to copy-and-paste view";
      s2 = "Switch back to interactive view";
      link.textContent = link.textContent.trim() == s1 ? s2: s1;
      toggle('browserTraceback', 'pastebinTraceback');
      return false;
    }
  </script>
  
</head>
<body>
<div id="summary">
  <h1>IntegrityError
       at /v1/user/profile</h1>
  <pre class="exception_value">(1452, &#x27;Cannot add or update a child row: a foreign key constraint fails (`badgr`.`authtoken_token`, CONSTRAINT `authtoken_token_user_id_35299eff_fk_users_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))&#x27;)</pre>
  <table class="meta">

    <tr>
      <th>Request Method:</th>
      <td>POST</td>
    </tr>
    <tr>
      <th>Request URL:</th>
      <td>https://api.staging.openbadges.education/v1/user/profile</td>
    </tr>

    <tr>
      <th>Django Version:</th>
      <td>3.2</td>
    </tr>

    <tr>
      <th>Exception Type:</th>
      <td>IntegrityError</td>
    </tr>


    <tr>
      <th>Exception Value:</th>
      <td><pre>(1452, &#x27;Cannot add or update a child row: a foreign key constraint fails (`badgr`.`authtoken_token`, CONSTRAINT `authtoken_token_user_id_35299eff_fk_users_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))&#x27;)</pre></td>
    </tr>


    <tr>
      <th>Exception Location:</th>
      <td><span class="fname">/badgr_server/venv/lib/python3.8/site-packages/MySQLdb/connections.py</span>, line 239, in query</td>
    </tr>

    <tr>
      <th>Python Executable:</th>
      <td>/badgr_server/venv/bin/uwsgi</td>
    </tr>
    <tr>
      <th>Python Version:</th>
      <td>3.8.14</td>
    </tr>
    <tr>
      <th>Python Path:</th>
      <td><pre>[&#x27;/badgr_server/apps&#x27;,
 &#x27;.&#x27;,
 &#x27;&#x27;,
 &#x27;/usr/local/lib/python38.zip&#x27;,
 &#x27;/usr/local/lib/python3.8&#x27;,
 &#x27;/usr/local/lib/python3.8/lib-dynload&#x27;,
 &#x27;/badgr_server/venv/lib/python3.8/site-packages&#x27;,
 &#x27;/badgr_server&#x27;]</pre></td>
    </tr>
    <tr>
      <th>Server time:</th>
      <td>Fri, 27 Sep 2024 15:24:49 +0200</td>
    </tr>
  </table>
</div>




<div id="traceback">
  <h2>Traceback <span class="commands"><a href="#" onclick="return switchPastebinFriendly(this);">
    Switch to copy-and-paste view</a></span>
  </h2>
  <div id="browserTraceback">
    <ul class="traceback">
      
        
        <li class="frame django">
          
            <code class="fname">/badgr_server/venv/lib/python3.8/site-packages/django/db/models/query.py</code>, line 581, in get_or_create
          

          
            <div class="context" id="c140600079575616">
              
                <ol start="574" class="pre-context" id="pre140600079575616">
                
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        Return a tuple of (object, created), where created is a boolean</pre></li>
                
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        specifying whether an object was created.</pre></li>
                
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        &quot;&quot;&quot;</pre></li>
                
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        # The get() needs to be targeted at the write database in order</pre></li>
                
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        # to avoid potential transaction consistency problems.</pre></li>
                
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        self._for_write = True</pre></li>
                
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        try:</pre></li>
                
                </ol>
              
              <ol start="581" class="context-line">
                <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>            return self.get(**kwargs), False</pre> <span>…</span></li>
              </ol>
              
                <ol start='582' class="post-context" id="post140600079575616">
                  
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>        except self.model.DoesNotExist:</pre></li>
                  
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>            params = self._extract_model_params(defaults, **kwargs)</pre></li>
                  
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>            # Try to create an object using passed params.</pre></li>
                  
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>            try:</pre></li>
                  
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>                with transaction.atomic(using=self.db):</pre></li>
                  
                  <li onclick="toggle('pre140600079575616', 'post140600079575616')"><pre>                    params = dict(resolve_callables(params))</pre></li>
                  
              </ol>
              
            </div>
          

          
            <div class="commands">
                
                    <a href="#" onclick="return varToggle(this, '140600079575616')"><span>&#x25b6;</span> Local vars</a>
                
            </div>
            <table class="vars" id="v140600079575616">
              <thead>
                <tr>
                  <th>Variable</th>
          …
            </div>
            <table class="vars" id="v140600079575616">
              <thead>
                <tr>
                  <th>Variable</th>
          …
```

You might be tempted to think that this is caused by the user already existing, but this is false. You can easily reproduce this by running the selenium test `signup.spec.js` a few times.

**Comment by timber-they** [comment]
To correct myself, to **reproduce** this, you seem to need to do the following:
1. Create a user via the UI
2. Delete the user via the staff interface
3. Try to create the same user again

**Comment by jona159** [comment]
@timber-they can you verify if this is still an issue? I ran the ```signup.spec.js``` successively for about 20 times without failure. Manually i could not reproduce the error on the current staging environment as well

**Comment by timber-they** [comment]
@jona159 as I said in my last comment, you need to delete the user via the staff interface, before verifying it and after having tried to log in before. Also, after deleting the user you shouldn't log out from the ui, but just navigate to the registration page directly. This is not done in the E2E test (since it's not quite a typical use case).
I just tried to reproduce it and curiously I couldn't reproduce at first try (in which I deleted the user from the staff details page), but was able to reproduce it on staging on second try (in which I deleted the user from the overview). I'm not entirely sure what's the reason it worked on the first try, but either way: It's still an issue on staging and this change should fix it.
