### ISSUE TITLE
server: cannot recreate user with the same email after deleting account

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-server#282]
Edit: I could not reproduce this on ```production``` yet, but on ```develop``` and ```staging```
It throws this error: 

```Internal Server Error: /v1/user/profile
api-1  | Traceback (most recent call last):
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 173, in __get__
api-1  |     rel_obj = self.field.get_cached_value(instance)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
api-1  |     return instance._state.fields_cache[cache_name]
api-1  | KeyError: 'user'
api-1  | 
api-1  | During handling of the above exception, another exception occurred:
api-1  | 
api-1  | Traceback (most recent call last):
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
api-1  |     response = get_response(request)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
api-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
api-1  |     return view_func(*args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
api-1  |     return self.dispatch(request, *args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
api-1  |     response = self.handle_exception(exc)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
api-1  |     self.raise_uncaught_exception(exc)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
api-1  |     raise exc
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
api-1  |     response = handler(request, *args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/apispec_drf/decorators.py", line 154, in wrapper
api-1  |     return wrapped(*args, **kwargs)
api-1  |   File "/badgr_server/apps/mainsite/utils.py", line 397, in wrapper
api-1  |     raise e
api-1  |   File "/badgr_server/apps/mainsite/utils.py", line 378, in wrapper
api-1  |     result = f(*args, **kw)  # execute the decorated function
api-1  |   File "/badgr_server/apps/badgeuser/api.py", line 134, in post
api-1  |     serializer.save()
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
api-1  |     self.instance = self.create(validated_data)
api-1  |   File "/badgr_server/apps/badgeuser/serializers_v1.py", line 90, in create
api-1  |     user = BadgeUser.objects.create(
api-1  |   File "/badgr_server/apps/badgeuser/managers.py", line 44, in create
api-1  |     if plaintext_password and not existing_email.user.password and not existing_email.verified:
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 187, in __get__
api-1  |     rel_obj = self.get_object(instance)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 154, in get_object
api-1  |     return qs.get(self.field.get_reverse_related_filter(instance))
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
api-1  |     raise self.model.DoesNotExist(
api-1  | badgeuser.models.BadgeUser.DoesNotExist: BadgeUser matching query does not exist.
```

**Comment by zven** [comment]
Just tested with the latest state on `develop`: After deleting my user via `Mein Profil` -> `Löschen`, I was able to create a new user with the same email address of the just deleted user.
