### ISSUE TITLE
server: PDF download from backpack fails

### ISSUE THREAD

**Issue by timber-they** [mint-o-badges/badgr-server#291]
The download of PDFs from my backpack fails on Staging with an error 500. The server logs this:
```
api-1  | Internal Server Error: /v1/earner/badges/pdf/P9TxpND5S06MjpMsjMO9ww
api-1  | Traceback (most recent call last):
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
api-1  |     response = get_response(request)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
api-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
api-1  |     return view_func(*args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
api-1  |     return self.dispatch(request, *args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
api-1  |     response = self.handle_exception(exc)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
api-1  |     self.raise_uncaught_exception(exc)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
api-1  |     raise exc
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
api-1  |     response = handler(request, *args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
api-1  |     return func(*args, **kwargs)
api-1  |   File "/badgr_server/apps/backpack/views.py", line 391, in pdf
api-1  |     name = get_name(badgeinstance)
api-1  |   File "/badgr_server/apps/mainsite/utils.py", line 587, in get_name
api-1  |     badgeuser = BadgeUser.objects.get(email=badgeinstance.recipient_identifier)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
api-1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
api-1  |     raise self.model.MultipleObjectsReturned(
api-1  | badgeuser.models.BadgeUser.MultipleObjectsReturned: get() returned more than one BadgeUser -- it returned 2!
```

**Comment by jona159** [comment]
@timber-they Could you check again with the current state of staging? I think this might be fixed, at least i couldnt reproduce and the error references code that are is longer present on staging

**Comment by zven** [comment]
@timber-they Is this ticket still up to date?
