### ISSUE TITLE
server: Awarding (old?) badges fails

### ISSUE THREAD

**Issue by timber-they** [mint-o-badges/badgr-server#292]
I awarded a rather old badge to myself and now my backpack doesn't load anymore. It fails with a server 500. Server logs:
```
api-1  | Internal Server Error: /v1/earner/badges
api-1  | Traceback (most recent call last):
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
api-1  |     response = get_response(request)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
api-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
api-1  |     return view_func(*args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
api-1  |     return self.dispatch(request, *args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
api-1  |     response = self.handle_exception(exc)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
api-1  |     self.raise_uncaught_exception(exc)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
api-1  |     raise exc
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
api-1  |     response = handler(request, *args, **kwargs)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/apispec_drf/decorators.py", line 123, in wrapper
api-1  |     return wrapped(*args, **kwargs)
api-1  |   File "/badgr_server/apps/backpack/api.py", line 97, in get
api-1  |     return super(BackpackAssertionList, self).get(request, **mykwargs)
api-1  |   File "/badgr_server/apps/entity/api.py", line 74, in get
api-1  |     return Response(serializer.data, headers=headers)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
api-1  |     ret = super().data
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
api-1  |     self._data = self.to_representation(self.instance)
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
api-1  |     return [
api-1  |   File "/badgr_server/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
api-1  |     self.child.to_representation(item) for item in iterable
api-1  |   File "/badgr_server/apps/backpack/serializers_v1.py", line 49, in to_representation
api-1  |     representation['extensions']["extensions:CompetencyExtension"] = obj.badgeclass.json['extensions:CompetencyExtension']
api-1  | KeyError: 'extensions:CompetencyExtension'
```

**Comment by jona159** [comment]
@timber-they what badge did you award? From the error, it appears to me like the badge could be broken

**Comment by zven** [comment]
@timber-they and @jona159 Is this still an issue?
