### ISSUE TITLE
Staging Table doesn't exist when trying to delete user

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-server#43]
When trying to delete a user on Staging, this fails:
![Image](https://github.com/mint-o-badges/badgr-server/assets/13370101/a3bc7047-8cb5-4f90-a166-05e844fb65ea)

The following error is logged:
```python
Internal Server Error: /staff/badgeuser/badgeuser/4/delete/
Traceback (most recent call last):
  File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/badgr_server/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/badgr_server/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/badgr_server/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'badgr.issuer_collectionbadgecontainer' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1838, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1859, in _delete_view
    deleted_objects, model_count, perms_needed, protected = self.get_deleted_objects([obj], request)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1833, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 118, in get_deleted_objects
    collector.collect(objs)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 181, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/deletion.py", line 223, in collect
    elif sub_objs:
  File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/query.py", line 278, in __bool__
    self._fetch_all()
  File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/badgr_server/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/badgr_server/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/badgr_server/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/badgr_server/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
```

**Comment by jona159** [comment]
I think we should try to revert the [collectionbadges PR](https://github.com/mint-o-badges/badgr-server/pull/28) in the backend first. I tried to create a new superuser on staging and got this warning: 

![Image](https://github.com/mint-o-badges/badgr-server/assets/65068389/4571b7fb-eb45-4211-93c4-f4dc4d57f228)

To find out which migrations were not applied i used: ```docker-compose exec api python /badgr_server/manage.py showmigrations --list```  which showed: 



![Image](https://github.com/mint-o-badges/badgr-server/assets/65068389/8f5a9aee-4c40-4ae9-9101-15cf6e7e03c3)

Migrations 65 -68 in the issuer app are the migrations for superbadges and collectionbadges, they were not applied. I hope that reverting the PR for collectionbadges then solves this issue. Maybe we can also think about automatically applying migrations.
