### ISSUE TITLE
Migrate Django to v3

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#51]
Right now the used Django version is 2.2.x which is pretty old and EOL.

Latest release is 4.2.6

most recent attempt: https://github.com/myBadges-org/badgr-server/blob/update-django/django-update.md

**Comment by timber-they** [comment]
@zven @jona159 doesn't this mean that this ticket should be ready for review? Or what exactly is there left to do?

**Comment by zven** [comment]
@timber-they Ah, it simply slipped my attention that @jona159 already did an upgrade. Please feel free to review the work.

**Comment by timber-they** [comment]
The build failure is also reproducible locally:
```bash
cp .docker/etc/settings_local.prod.py.example .docker/etc/settings_local.py
docker compose -f docker-compose.prod.yml up --no-deps --build api
```
fails with:
```bash
69.38   Running setup.py install for uwsgi: started
69.53   Running setup.py install for uwsgi: finished with status 'error'
69.53   error: subprocess-exited-with-error
69.53   
69.53   × Running setup.py install for uwsgi did not run successfully.
69.53   │ exit code: 1
69.53   ╰─> [25 lines of output]
69.53       /usr/local/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'descriptions'
69.53         warnings.warn(msg)
69.53       running install
69.53       using profile: buildconf/default.ini
69.53       detected include path: ['/usr/lib/gcc/x86_64-linux-gnu/8/include', '/usr/local/include', '/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed', '/usr/include/x86_64-linux-gnu', '/usr/include']
69.53       Patching "bin_name" to properly install_scripts dir
69.53       detected CPU cores: 20
69.53       Traceback (most recent call last):
69.53         File "<string>", line 2, in <module>
69.53         File "<pip-setuptools-caller>", line 34, in <module>
69.53         File "/tmp/pip-install-uub83int/uwsgi_3368e0fe85ab41be8c52ff00824add74/setup.py", line 117, in <module>
69.53           setup(
69.53         File "/badgr_server/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
69.53           return distutils.core.setup(**attrs)
69.53         File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
69.53           dist.run_commands()
69.53         File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
69.53           self.run_command(cmd)
69.53         File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
69.53           cmd_obj.run()
69.53         File "/tmp/pip-install-uub83int/uwsgi_3368e0fe85ab41be8c52ff00824add74/setup.py", line 79, in run
69.53           uc.build_uwsgi(conf)
69.53         File "/tmp/pip-install-uub83int/uwsgi_3368e0fe85ab41be8c52ff00824add74/uwsgiconfig.py", line 325, in build_uwsgi
69.53           print("configured CFLAGS: %s" % ' '.join(cflags))
69.53       TypeError: sequence item 15: expected str instance, NoneType found
69.53       [end of output]
69.53   
69.53   note: This error originates from a subprocess, and is likely not a problem with pip.
69.54 error: legacy-install-failure
69.54 
69.54 × Encountered error while trying to install package.
69.54 ╰─> uwsgi
69.54 
69.54 note: This is an issue with the package mentioned above, not pip.
69.54 hint: See above for output from the failure.
69.78 WARNING: You are using pip version 22.0.4; however, version 24.0 is available.
69.78 You should consider upgrading via the '/badgr_server/venv/bin/python -m pip install --upgrade pip' command.
------
failed to solve: executor failed running [/bin/sh -c pip install -r requirements.txt]: exit code: 1
```

**Comment by mpfeil** [comment]
@timber-they maybe checkout this stackoverflow answer https://stackoverflow.com/a/73870932

The action log also says that it was using `Legacy ...` https://github.com/mint-o-badges/badgr-server/actions/runs/8690616613/job/23830961755#step:6:2411

**Comment by timber-they** [comment]
@mpfeil this seems to have worked, thanks for the hint!
